[package]
name = "tametsi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
steamlocate = "0.1.4"
roxmltree = "0.14.1"